language: go
go:
  1.7.x

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: MMN+YTQBywiKTDjVUKECFkgfhiuHEgUjnh76930KteVic+6jIv+FZqFehb/90LgI6bIdE2fj9A15oJBc9c/XnLpWzxsCM/oc+8OMvGOsqnGjwC51qxqVrlORB5LKLg5Gc2+7BHWPDEoI7CNJxu5WALWQUN6m3WKnpeCq5WOXFxjRaiS4V5yLF2bAnjUudzY0cyp/nhDfItyfTSIS8Me7/UV1UMo7ZaIu6z+ZFuhjjMQfSNl27JPiCxpJy6vuFqFy4Mten3rGeQLzBR1XgS92Iq9nQ4p97aFOoWVx62DICydJMwwwT4Dl5zK+BhqPq4qf7WzHQsPsQ6TFaix/rfx+XmnBJVL6+bSsgIr2Wn6ay+Zk7BO9J7cwgqjvntGDscCzE8N1kt5Ik9cM3nwLMy3tBybYaTqg8w1vB3C2YzyZP0LZwb3hnFWqUJRHukJi9Prg9gWpQ/C+oCTaXa/8u6+aNlzBGlrIOxF4Hk2xRBk7fanAyx9A2jwmj4iHg3AVJSAJVGgXc502MGwIcQCz/5IToRUZfyvu44GAjjVbiXhC62X2tXk0EfNpzyG6k3M+If/SHNuabl8jTzd66adeDourTHUDjCoSIi1nC2xx+MZI6B2b/SIzrRdLVRAqve07D0qacFjl35CI+hEn6QlAkbM+3dtSfaAFPlMf0VUrNMXIwFU=
  file: fettle
  on:
    repo: ahoka/fettle
    tags: true
